resources:
- name: dockerfile-repo
  type: git
  source:
    uri: http://training-box-gogs/student/lab-assets
    branch: master
- name: golang-image
  type: docker-image
  source:
    repository: training-box-docker-registry:5000/student/golang-image
    insecure_registries: [ "training-box-docker-registry:5000" ]
jobs:
  - name: build-image
    plan:
    - get: dockerfile-repo
    - put: golang-image
      params: {build: dockerfile-repo}
      get_params: {rootfs: true}
